version: '3.1'
services:
  project3-server:
    image: gobananas:latest
    container_name: project3-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 4000:4000
    environment:
      PORT: 4000
      NODE_ENV: production

# CLI Access:
# docker-compose run --rm mongo-server mongo --host mongo-server