
version: "3.7"
services:
  gobananas:
    build: ../../../
    image: 664970746922.dkr.ecr.us-east-1.amazonaws.com/gobananas:0.1.0
    ports:
    - 8080:8080
    env_file:
    - hidden.env
    labels:
      aws.ecs.fargate.deploy: 1
    #x-fargate-secrets:
      #KEY: value
